export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const FILL_OUT_INFO = 'FILL_OUT_INFO'
export const IS_CHECKOUT = 'IS_CHECKOUT'
export const PAY_NOW = 'PAY_NOW'
export const SET_VENDOR = 'SET_VENDOR'